[general]
import = [
  "./tokyonight_night.toml"
]
live_config_reload = true

[window]
dynamic_padding = true

[scrolling]
history = 0

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
#normal = { family = "Iosevka Nerd Font", style = "Regular" }
#normal = { family = "FiraCode Nerd Font", style = "Regular" }
#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 9

[cursor]
style = { blinking = "Never" }
